### *ES Settings* ###

### Create index
PUT http://127.0.0.1:9200/items
Content-Type: application/json

{
  "settings": {
    "index": {
      "number_of_shards": 2,
      "number_of_replicas": 2
    }
  }
}

### Check index
GET http://127.0.0.1:9200/items
Content-Type: application/json

### *API* ###

### Create item
POST http://127.0.0.1:8000/items?access_token=31e31d2fdd27b81ac7e8ad525a5bb0c35824af0c
Content-Type: application/json

{
  "title": "Best practices",
  "description": {
    "plain_text": "Super powerful guide",
    "html": "<p>Super powerful guide<p>"
  },
  "pictures": [
    {
      "url": "http://127.0.0.1:9000/pic.png"
    }
  ],
  "video": "http://127.0.0.1:9000/video.mp4",
  "price": 100.0,
  "available_quantity": 1000,
  "sold_quantity": 500,
  "status": "active"
}

### Get items
POST http://127.0.0.1:8000/items/search
Content-Type: application/json

{
  "not_equals": [
    {
      "field": "status",
      "value": "inactive"
    }
  ],
  "equals": [
    {
      "field": "available_quantity",
      "value": 1000
    }
  ]
}

### Get items by id

GET http://127.0.0.1:8000/items/FjxbPXcBpwkRtvVMlq1U
Content-Type: application/json

### Patch item
PATCH http://127.0.0.1:8000/items/FjxbPXcBpwkRtvVMlq1U?access_token=31e31d2fdd27b81ac7e8ad525a5bb0c35824af0c
Content-Type: application/json

{
  "id": "FjxbPXcBpwkRtvVMlq1U",
  "title": "Best practices ver 2.0"
}

### Delete item
DELETE http://127.0.0.1:8000/items/7C35MncBiikUn6nE-UQ9?access_token=31e31d2fdd27b81ac7e8ad525a5bb0c35824af0c
Content-Type: application/json


### Get items by id

GET http://127.0.0.1:8000/health
Content-Type: application/json
